companies/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='companies-home'),
    path('about/', views.about, name = 'companies-about'),
    path('ajax/load-subcategories/', views.load_subcategories, name='ajax_load_subcategories'),
]

startup_directory/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from companies import views as company_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('companies.urls')),
    path('register/', company_views.register, name='register'),
    path('profile/', company_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='companies/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='companies/logout.html'), name='logout'),
    path('password-reset/',
          auth_views.PasswordResetView.as_view(
            template_name='companies/password_reset.html'
          ),
          name='password_reset'),
    path('password-reset/done/',
          auth_views.PasswordResetDoneView.as_view(
            template_name='companies/password_reset_done.html'
          ),
          name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(
            template_name='companies/password_reset_confirm.html'
          ),
          name='password_reset_confirm'),
    path('password-reset-complete',
          auth_views.PasswordResetCompleteView.as_view(
            template_name='companies/password_reset_complete.html'
          ),
          name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

companies/models.py
from django.db import models
from django.contrib.auth.models import User
from custom_cities.models import City, Pincode
from phonenumber_field.modelfields import PhoneNumberField
from PIL import Image

class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)

    def __str__(self):
        return f'{self.name}'

class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=250, unique=True)

    def __str__(self):
        return f'{self.name}'

class CompanyProfile(models.Model):
    DIGITAL_FIELD = 'DF'
    ENGINEERING_FIELD = 'ED'
    LOCAL_BUSINESS = 'LB'
    COMPANY_FIELDS = [
        (DIGITAL_FIELD, 'IT, Consulting and Product Development'),
        (ENGINEERING_FIELD, 'Engineering and Design'),
        (LOCAL_BUSINESS, 'Local Business'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    contact_person = models.CharField(max_length=100, blank=False, null=False, default='Owner')
    contact_number = PhoneNumberField(null=False, blank=False, default='+910123456789')
    website_url = models.URLField(max_length=250, default='#')
    logo = models.ImageField(default='default.jpg', upload_to='profile_pics')
    services = models.TextField(blank=True, null=True)
    address = models.CharField(max_length=500, blank=False, null=False, default='Gandhinagar')
    city = models.ForeignKey(City, models.SET_NULL, blank=True, null=True)
    pincode = models.ForeignKey(Pincode, models.SET_NULL, blank=True, null=True)
    company_field = models.CharField(max_length=100, choices=COMPANY_FIELDS, default=DIGITAL_FIELD)
    company_category = models.ForeignKey(Category, models.SET_NULL, blank=True, null=True, default=Category.objects.first().id)
    company_subcategory = models.ForeignKey(SubCategory, models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'{ self.user.username } Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.logo.path)

        if img.height > 300 or img.width > 300:
            img_output_size = (300, 300)
            img.thumbnail(img_output_size)
            img.save(self.logo.path)

        

companies/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import CompanyProfile, SubCategory
from custom_cities.models import City, State

class CompanyRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class CompanyUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class CompanyProfileUpdateForm(forms.ModelForm):
    website_url = forms.URLField(help_text='http://')
    services = forms.CharField(widget=forms.Textarea, help_text='Add each service in next line.')
    state = forms.ModelChoiceField(State.objects.all())

    def __init__(self, *args, **kwargs):
        super(CompanyProfileUpdateForm, self).__init__(*args, **kwargs)
        self.fields['state'].required = False
        self.fields['city'].required = True
        self.fields['website_url'].required = False
        self.fields['address'].required = False
        self.fields['company_subcategory'].queryset = SubCategory.objects.none()
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

        if 'company_category' in self.data:
            try:
                category_id = int(self.data.get('company_category'))
                self.fields['company_subcategory'].queryset = SubCategory.objects.filter(category_id=category_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['company_subcategory'].queryset = self.instance.company_category.subcategory_set.order_by('name')

    def clean(self):
        address = self.cleaned_data.get('address')
        website_url = self.cleaned_data.get('website_url')
        if not address and not website_url:
            raise forms.ValidationError('One of fields is required')
        return self.cleaned_data

    class Meta:
        model = CompanyProfile
        fields = ['logo', 'contact_person', 'contact_number', 'company_field', 'company_category', 'company_subcategory', 'address', 'city', 'state', 'pincode', 'website_url', 'services']

companies/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import CompanyRegisterForm, CompanyUpdateForm, CompanyProfileUpdateForm
from django.contrib.auth.models import User
from django.db.models import Prefetch
from .models import CompanyProfile, Category, SubCategory
from .snippets import NamePaginator
from custom_cities.models import Pincode, City, State, Country

def home(request):
    if request.method == 'POST':
        city_id = request.POST.get('city')
        city = City.objects.get(pk=city_id)
        company_field = request.POST.get('company_field')
        category_id = request.POST.get('category')
        category = Category.objects.get(pk=category_id)
        companies = User.objects.filter(is_staff=False, companyprofile__city=city, companyprofile__company_category=category).prefetch_related(
                                                        Prefetch('companyprofile',
                                                                  queryset = CompanyProfile.objects.filter(city=city_id, company_category_id=category_id)
                                                        )
                                                    )
    else:
        if request.GET.get('city') and request.GET.get('category'):
            city_id = request.GET.get('city')
            city = City.objects.get(pk=city_id)
            category_id = request.GET.get('category')
            category = Category.objects.get(pk=category_id)
            companies = User.objects.filter(is_staff=False, companyprofile__city=city, companyprofile__company_category=category).prefetch_related(
                                                            Prefetch('companyprofile',
                                                                      queryset = CompanyProfile.objects.filter(city=city_id, company_category_id=category_id)
                                                            )
                                                        )
        else:
            city = City.objects.get(pk=1)
            company_field = 'DF'
            category = Category.objects.first()
            companies = User.objects.filter(is_staff=False, companyprofile__city=1, companyprofile__company_category=category).prefetch_related(
                                                                Prefetch('companyprofile',
                                                                          queryset = CompanyProfile.objects.filter(city=1, company_category=category)
                                                                )
                                                            )
    cities = City.objects.values('id', 'name')
    company_fields = CompanyProfile.COMPANY_FIELDS
    categories = Category.objects.all()
    paginator = NamePaginator(companies, on='username', per_page=25)
    try:
        page = int(request.GET.get('companies', '1'))
    except ValueError:
        page = 1

    try:
        page = paginator.page(page)
    except (InvalidPage):
        page = paginator.page(paginator.num_pages)
    context = { 'companies': page, 'city': city, 'cities': cities, 'categories': categories, 'category': category }
    return render(request, 'companies/home.html', context)

def about(request):
    context = { 'title': 'about' }
    return render(request, 'companies/about.html', context)

def register(request):
    if request.method == 'POST':
        form = CompanyRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for { username }!')
            return redirect('login')
    else:
        form = CompanyRegisterForm()
    return render(request, 'companies/register.html', { 'form': form })


@login_required
def profile(request):
    pincode = request.user.companyprofile.pincode.pincode if request.user.companyprofile.pincode else ''
    if request.method == 'POST':
        c_form = CompanyUpdateForm(request.POST, instance=request.user)
        cp_form = CompanyProfileUpdateForm(request.POST, request.FILES, instance=request.user.companyprofile)
        if c_form.is_valid() and cp_form.is_valid():
            c_form.save()
            uncommitted_cp_form = cp_form.save(commit=False)
            if request.POST['city']:
                pin = Pincode.objects.get_or_create(city_id=request.POST['city'], pincode=request.POST['input_pincode'])[0]
                uncommitted_cp_form.pincode = pin
            if request.POST['input_city']:                
                st = State.objects.get(name=request.POST['input_state'])
                cit = City.objects.get_or_create(state=st, name=request.POST['input_city'])[0]
                pin = Pincode.objects.get_or_create(city=cit, pincode=request.POST['input_pincode'])[0]
                uncommitted_cp_form.city = cit
                uncommitted_cp_form.pincode = pin
            if request.POST['input_company_category'] or request.POST['input_company_subcategory']:
                com_cat = Category.objects.get_or_create(name=request.POST['input_company_category'])[0]
                import ipdb; ipdb.set_trace()
                com_subcat = SubCategory.objects.get_or_create(category=com_cat, name=request.POST['input_company_subcategory'])[0]
                uncommitted_cp_form.company_category = com_cat
                uncommitted_cp_form.company_subcategory = com_subcat
            uncommitted_cp_form.save()
            pincode = request.user.companyprofile.pincode.pincode
            messages.success(request, f'Your profile has been updated!')
            return redirect('profile')
    else:
        c_form = CompanyUpdateForm(instance=request.user)
        cp_form = CompanyProfileUpdateForm(instance=request.user.companyprofile)
    context = {
        'c_form': c_form,
        'cp_form': cp_form,
        'pincode': pincode
    }
    return render(request, 'companies/profile.html', context)

def load_subcategories(request):
    category_id = request.GET.get('company_category')
    sub_categories = SubCategory.objects.filter(category_id=category_id).order_by('name')
    return render(request, 'companies/subcategory_dropdown_list_options.html', {'sub_categories': sub_categories})

companies/templates/companies/about.html
{% extends 'companies/base.html' %}
{% block content %}
    <h1>Startups Directory - About</h1>
{% endblock %}

companies/templates/companies/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'companies/main.css' %}">

    {% if title %}
        <title>Startups Directory - {{ title }}</title>
    {% else %}
        <title>Startups Directory</title>
    {% endif %}
</head>
<body>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'companies-home' %}">Startups Directory</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'companies-home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'companies-about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="companies-container">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block extrahead %}{% endblock extrahead %}
          {% block content %}{% endblock content %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

companies/templates/companies/home.html
{% extends 'companies/base.html' %}
{% load static %}
{% block extrahead %}<link rel="stylesheet" type="text/css" href="{% static 'companies/home.css' %}">{% endblock extrahead %}
{% block content %}

    <div class="index-block">
        <div class="main-header"><h1>Startups Directory</h1></div>

        <div class="search_forms">


            <form class="choices_select_form" method="POST" action="{% url 'companies-home' %}"/>
                {% csrf_token %}
                <div class="cities_dropdown">
                    <select name = "city">
                        {% for citiy in cities %}
                            <option value="{{ citiy.id }}"
                                    {% if city.name == citiy.name %} selected="selected" {% endif %}>
                                    {{ citiy.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="categories_dropdown">
                    <select name = "category">
                        {% for cat in categories %}
                            <option value="{{ cat.id }}"
                                    {% if category == cat %} selected="selected" {% endif %}>
                                    {{ cat.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                <div>
                    <input type="submit"  value="Search" />
                </div>
            </form>

        </div>

        <div class="pagination">
            Browse by title:
            {% for p in companies.paginator.pages %}

              {% ifequal p companies %}
                  <div><span class="selected">{{ companies }}</span></div>
              {% else %}
                  <div><a href="?companies={{ p.number }}&city={{ city.id }}&category={{ category.id }}">
                      {{ p }}
                  </a></div>
              {% endifequal %}

            {% endfor %}
        </div>

        <div id="companies">

            <div id="Bengaluru">
                <div class="city-header"><h2>{{ city.name }}</h2></div>
                <div class="row">
                    {% for company in companies.object_list %}
                        <div class="index_column">
                            <div class="logo_services">
                                <div class="company_logo"><a href="{% if company.companyprofile.website_url %} {{ company.companyprofile.website_url }} {% else %} http://maps.google.com/?q={{company.companyprofile.address}} {{company.companyprofile.city.name}} {% endif %}"
                                   target="_blank">
                                   <img class="bengaluru-images" src="{{ company.companyprofile.logo.url }}">
                                </a></div>
                                <div class="services">{{ company.companyprofile.services|linebreaks }}</div>
                            </div>
                            <div class="company_name"><h6>{{ company.username }}</h6></div>
                            <div class="company_contact_number"><h6>{{ company.companyprofile.contact_number }}</h6></div>
                            <br><br>
                        </div>
                            {% if forloop.counter|divisibleby:2 %}
                </div>
                <div class="row">
                            {% endif %}
                    {% endfor %}
                </div>
            </div>

        </div>



    </div>
{% endblock content %}

companies/templates/companies/login.html
{% extends 'companies/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Log In
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">
                    Login
                </button>
                <small class="text-muted ml-2">
                    <a href="{% url 'password_reset' %}">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class=text-muted>Create a new account? <a class="ml-2" href="{% url 'register' %}">Sign Up</a></small>
        </div>
    </div>
{% endblock content %}

companies/templates/companies/logout.html
{% extends 'companies/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="border-top pt-3">
            <a href="{% url 'login' %}">Log In Again</a>
        </div>
    </div>
{% endblock content %}

companies/templates/companies/password_reset.html
{% extends 'companies/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Reset Password
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">
                    Request Password Reset
                </button>
            </div>
        </form>
    </div>
{% endblock content %}

companies/templates/companies/password_reset_complete.html
{% extends 'companies/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="alert alert-info">
        Password has been set.
    </div>
    <a href="{% url 'login' %}">Sign In</a>
{% endblock content %}

companies/templates/companies/password_reset_confirm.html
{% extends 'companies/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Reset Password
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">
                    Reset Password
                </button>
            </div>
        </form>
    </div>
{% endblock content %}

companies/templates/companies/password_reset_done.html
{% extends 'companies/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="alert alert-info">
        Email has been sent.
    </div>
{% endblock content %}

companies/templates/companies/profile.html
{% extends 'companies/base.html' %}
{% load crispy_forms_tags %}
{{ form.media.css }}
{% block content %}
    <div class="content-section">
        <div class="content-section">
          <div class="media">
            <img class="rounded-circle account-img" src="{{ user.companyprofile.logo.url }}">
            <div class="media-body">
              <h2 class="account-heading">{{ user.username }}</h2>
              <p class="text-secondary">{{ user.email }}</p>
            </div>
          </div>
          {% if cp_form.errors %}
    {% for field in cp_form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in cp_form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
          <form method="POST" id="companyProfileForm" data-subcategories-url="{% url 'ajax_load_subcategories' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    User Info
                </legend>
                {{ c_form|crispy }}

                <label for="id_logo">Logo</label>
                <p>{{ cp_form.logo }}</p>

                <label for="id_contact_person">Contact Person</label>
                <p>{{ cp_form.contact_person }}</p>

                <label for="id_contact_number">Contact Number</label>
                <p>{{ cp_form.contact_number }}</p>

                <label for="id_company_field">Field of Business</label>
                <p>{{ cp_form.company_field }}</p>

                <div id="company_category_dropdown">
                    <label for="id_company_category">Category</label>
                    <p>{{ cp_form.company_category }}</p>
                </div>

                <div><a href="javascript:void(0);" onclick="toggleCategoryInputDisplay();">Your field of business not in the list?</a></div><br>
                <div id="hidden_visible_category_input" style="display: none;">
                    <label for="input_company_category">Field of business</label>
                    <input id="input_company_category" type="text" name="input_company_category">
                </div><br>

                <div id="company_subcategory_dropdown">
                    <label for="id_company_subcategory">Sub Category</label>
                    <p>{{ cp_form.company_subcategory }}</p>
                </div>

                <div id="subcategory_present_text"><a href="javascript:void(0);" onclick="toggleSubCategoryInputDisplay();">Your subcategory of business not in the list?</a></div><br>
                <div id="hidden_visible_subcategory_input" style="display: none;">
                    <label for="input_company_subcategory">SubCategory</label>
                    <input id="input_company_subcategory" type="text" name="input_company_subcategory">
                </div><br>

                <label for="id_address">Address</label>
                <p>{{ cp_form.address }}</p>

                <label for="id_city">City</label>
                <p>{{ cp_form.city }}</p>

                <div><a href="javascript:void(0);" onclick="toggleCityInputDisplay();">Your city not present in the list?</a></div><br>
                <div id="hidden_visible_city_input" style="display: none;">
                    <label for="id_state">State</label>
                    <p>{{ cp_form.state }}</p>
                    <label for="input_city">City</label>
                    <input id="input_city" type="text" name="input_city">
                </div><br>

                <div>
                    <label for="input_pincode">Pincode</label>
                    <input id="input_pincode" type="text" name="input_pincode" value="{{ pincode }}">                
                </div><br>

                <label for="id_website_url">Website URL</label>
                <p>{{ cp_form.website_url }}</p>
                <p>{{ cp_form.website_url.help_text }}</p>

                <label for="id_location">Services</label>
                <p>{{ cp_form.services }}</p>
                <p>{{ cp_form.services.help_text }}</p>

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">
                    Update
                </button>
            </div>
        </form>
        </div>

    </div>
    <script type="text/javascript">
        const toggleCityInputDisplay = () => {
            let hidden_visible_city = document.getElementById('hidden_visible_city_input');
            if (hidden_visible_city.style.display == 'none') {
                hidden_visible_city.style.display = 'block';
                document.getElementById('input_city').setAttribute('required', '');
            } else {
                hidden_visible_city.style.display = 'none';
                document.getElementById('input_city').removeAttribute('required');
                document.getElementById('input_city').value = "";
            }
        }

        const toggleCategoryInputDisplay = () => {
            let hidden_visible_category = document.getElementById('hidden_visible_category_input');
            let hidden_visible_subcategory = document.getElementById('hidden_visible_subcategory_input');
            if (hidden_visible_category.style.display == 'none') {
                document.getElementById('company_category_dropdown').style.display = 'none';
                document.getElementById('id_company_category').selectedIndex = -1;
                document.getElementById('subcategory_present_text').style.display = 'none';
                document.getElementById('company_subcategory_dropdown').style.display = 'none';
                document.getElementById('id_company_subcategory').selectedIndex = -1;
                hidden_visible_category.style.display = 'block';
                hidden_visible_subcategory.style.display = 'block';
                document.getElementById('input_company_category').setAttribute('required', '');
                document.getElementById('input_company_subcategory').setAttribute('required', '');
            } else {
                hidden_visible_category.style.display = 'none';
                hidden_visible_subcategory.style.display = 'none';
                document.getElementById('company_category_dropdown').style.display = 'block';
                document.getElementById('subcategory_present_text').style.display = 'block';
                document.getElementById('company_subcategory_dropdown').style.display = 'block';
                document.getElementById('input_company_category').removeAttribute('required');
                document.getElementById('input_company_subcategory').removeAttribute('required');
                document.getElementById('input_company_category').value = "";
                document.getElementById('input_company_subcategory').value = "";
            }
        }

        const toggleSubCategoryInputDisplay = () => {
            let hidden_visible_category = document.getElementById('hidden_visible_subcategory_input');
            if (hidden_visible_category.style.display == 'none') {
                document.getElementById('company_subcategory_dropdown').style.display = 'none';
                document.getElementById('id_company_subcategory').selectedIndex = -1;
                hidden_visible_category.style.display = 'block';
                document.getElementById('input_company_subcategory').setAttribute('required', '');
            } else {
                hidden_visible_category.style.display = 'none';
                document.getElementById('company_subcategory_dropdown').style.display = 'block';
                document.getElementById('input_company_subcategory').removeAttribute('required');
                document.getElementById('input_company_subcategory').value = "";
            }
        }

        $("#id_company_category").change(function () {
          var url = $("#companyProfileForm").attr("data-subcategories-url"); 
          var categoryId = $(this).val();

          $.ajax({                       
            url: url,                    
            data: {
              'company_category': categoryId
            },
            success: function (data) {   
              $("#id_company_subcategory").html(data);
            }
          });

        });
    </script>
{% endblock content %}

companies/templates/companies/subcategory_dropdown_list_options.html
<option value="">---------</option>
{% for sub_category in sub_categories %}
<option value="{{ sub_category.pk }}">{{ sub_category.name }}</option>
{% endfor %}